Host legion
    HostName legion.local
    User zzhxwt1
    ServerAliveInterval 30
    ServerAliveCountMax 5
    Compression yes

Host legion.net
    HostName legion.net.local
    User zzhxwt1
    ServerAliveInterval 30
    ServerAliveCountMax 5
    Compression yes
