Host legion
    HostName legion.local
    ServerAliveInterval 30
    ServerAliveCountMax 5
    Compression yes

Host legion.net
    HostName legion.net.local
    ServerAliveInterval 30
    ServerAliveCountMax 5
    Compression yes
